stages:
  unzip:
    cmd: python ./unzip.py -c ./configs/prepare/unzip.yml
    deps:
      - ./configs/prepare/unzip.yml
      - ./unzip.py
      - ./data/raw-data/made-cv-2021-contest-01-facial-landmarks.zip
    outs:
      - ./data/test-train/contest01_data
  extract_train_emb:
    cmd: python ./compute_embeddings.py -c ./configs/extract_features/ext_features.yml
    deps:
      - ./compute_embeddings.py
      - ./configs/extract_features/ext_features.yml
      - ./data/test-train/contest01_data/train
      - ./face_landmarks
    outs:
      - ./data/features/train_emb.pickle
  download_data:
    cmd:
      kaggle competitions download -c made-cv-2021-contest-01-facial-landmarks
      -p ./data/raw-data/
    outs:
      - ./data/raw-data/made-cv-2021-contest-01-facial-landmarks.zip:
          persist: true
  train:
    cmd: python ./main_train.py -c ./configs/train/train.yml --fast_dev_run
    deps:
      - ./configs/train/train.yml
      - ./face_landmarks/
      - ./main_train.py
      - ./model/
      - .\data\test-train/contest01_data/train
    params:
      - params.py:
          - LossParams
          - OptimizerParams
          - TrainParams
    outs:
      - ./exp/train
