stages:
  unzip:
    cmd: python ./unzip.py -c ./configs/prepare/unzip.yml
    deps:
      - ./configs/prepare/unzip.yml
      - ./unzip.py
      - ./data/raw-data/made-cv-2021-contest-01-facial-landmarks.zip
    outs:
      - ./data/test-train/contest01_data
  extract_train_emb:
    cmd: python ./compute_embeddings.py -c ./configs/extract_features/ext_features.yml
    deps:
      - ./compute_embeddings.py
      - ./configs/extract_features/ext_features.yml
      - ./data/test-train/contest01_data/train
      - ./face_landmarks
    outs:
      - ./data/features/train_emb.pickle
  download_data:
    cmd: gdown --id 19905pDRrnX5YMdw-mvDZadJdUuzh_w2e -O ./data/raw-data/made-cv-2021-contest-01-facial-landmarks.zip
    outs:
      - ./data/raw-data/made-cv-2021-contest-01-facial-landmarks.zip:
          persist: true
          cache: false
  train:
    cmd: python ./main_train.py -c ./configs/train/train.yml
    deps:
      - ./configs/train/train.yml
      - ./face_landmarks/
      - ./main_train.py
      - ./model/
      - ./data/test-train/contest01_data/train
    params:
      - params.py:
          - LossParams
          - OptimizerParams
          - TrainParams
    outs:
      - ./exp/train
  test-run:
    cmd:
      python ./main_train.py -c ./configs/train/train.yml --fast_dev_run --exp_dir
      ./exp/test_run --valid_batch_size 16 --train_batch_size 16
    deps:
      - ./configs/train/train.yml
      - ./data/test-train/contest01_data/train
      - ./face_landmarks/
      - ./main_train.py
      - ./model/
    params:
      - params.py:
          - LossParams
          - OptimizerParams
          - TrainParams
    outs:
      - ./exp/test_run
